import { NextUIProvider } from '@nextui-org/react'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { ReactNode } from 'react'
import { Toaster } from 'sonner'

import './globals.scss'
import { Providers } from './providers'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				<Providers>
					<NextUIProvider>
						{children}

						<Toaster
							theme='light'
							position='bottom-right'
							duration={1500}
						/>
					</NextUIProvider>
				</Providers>
			</body>
		</html>
	)
}
